# These are supported funding model platforms

github: ondratu
custom: ["https://www.paypal.com/cgi-bin/webscr?cmd=_donations&business=4F4EJ3SV8JGYJ&item_name=Formiko+editor&currency_code=EUR&source=url", paypal]
